### ISSUE TITLE
Can not run pre release v1.1.0-1

### ISSUE THREAD

**Issue by karladler** [koresar/graphql-upload-minimal#2]
Error: Cannot find module './processRequestLambda

**Comment by koresar** [comment]
How to reproduce?

**Comment by wowczarczyk** [comment]
Same here, just include:
`"graphql-upload-minimal": "1.1.0-1",`
in package.json and you'll get:

![image](https://user-images.githubusercontent.com/1281649/86912776-df224980-c11d-11ea-956a-38f7b5adb71c.png)

during startup

**Comment by wowczarczyk** [comment]
I can see the file is not present in master: https://github.com/koresar/graphql-upload-minimal/tree/master/public

**Comment by koresar** [comment]
OMG. That's a horrible typo which was not picked up by tests.
The bug was fixed now.
Sorry about this.
Please, try again. `npm i graphql-upload-minimal@next`

**Comment by wowczarczyk** [comment]
It is fine now, thanks!

**Comment by koresar** [comment]
@wowczarczyk but does it work? :) Does it solve your problem?
If not, tell me what's needed.

**Comment by wowczarczyk** [comment]
Well, not entirely tbh, as I am using Nest.js with GraphQLmodule (based on apollo-server) and the trick with "overriding require" for `graphql-upload` does not seem to work

**Comment by koresar** [comment]
I'm not using ApolloServer. Maybe that's why I'm OK.
Uh. Frameworks. Always get in your way.
Not sure how else I can help.
